<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
     <AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="2.2.0" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="4.0.100.7" />
    <PackageReference Include="AWSSDK.SimpleEmailV2" Version="4.0.102.1" />
    <PackageReference Include="MailKit" Version="4.17.0" />
  </ItemGroup>

</Project>
